# Generated by Django 5.2.17 on 2026-09-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dance', 'Dance'), ('music', 'Music'), ('theatre', 'Theatre'), ('football', 'Football'), ('basketball', 'Basketball'), ('swimming', 'Swimming')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Format: HH:MM:SS, e.g. 01:30:00.')),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of places offered.')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.instructor')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activities.activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activities.member')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(related_name='activities', through='activities.Enrollment', to='activities.member'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rooms', to='activities.instructor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='main_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_activities', to='activities.room'),
        ),
        migrations.AddField(
            model_name='activity',
            name='secondary_rooms',
            field=models.ManyToManyField(blank=True, related_name='secondary_activities', to='activities.room'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('member', 'activity'), name='unique_member_per_activity'),
        ),
    ]
